### ISSUE TITLE
Update libraries in requirements.txt

### ISSUE THREAD

**Issue by jonathanstegall** [MinnPost/salesforce-stripe#13]
There's a branch for this here: https://github.com/MinnPost/salesforce-stripe/tree/update-libraries

However, just updating all the libraries and pushing it to the test version broke stuff. I haven't yet figured out which libraries cause the breakage, but we need to move carefully.

**Comment by x110dc** [comment]
I'd be most careful about upgrading the Flask and Celery libraries as I think there have been lots of changes there.

**Comment by jonathanstegall** [comment]
We have a branch where I hope to incorporate the Texas Trib changes here: https://github.com/MinnPost/salesforce-stripe/tree/refactor. While they don't only upgrade the libraries, they do indeed upgrade them.

**Comment by jonathanstegall** [comment]
If we can ever get all of the branch in edit-from-texas, this would be done.
